services:
  react:
    container_name: react
    build: ./
    volumes:
      - react-volume:/var/www/html
    networks:
      - roadilog-network

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - react
    networks:
      - roadilog-network

volumes:
  react-volume:

networks:
  roadilog-network:
    external: true